web:
  image: springdb
  command: docker run --detach -volumes-from --name=test-mysql --env="MYSQL_ROOT_PASSWORD=root" mysql
  links:
    - db
  ports:
    - "8181:8181"
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: dojdb
